#!/usr/bin/env bash
# Create the Entra app registration for audit.wantnot.nunan.com (delegated, public client).
# Adapted from wantnot/infra/05-audit-app.sh for the standalone audit repo.
#
# Usage:
#   ./tools/create_audit_app.sh                 # uses AUDIT_HOST, RG, SWA_NAME defaults
#   AUDIT_HOST=audit.wantnot.nunan.com ./tools/create_audit_app.sh
#   AUDIT_HOST=localhost RG=rg-wantnot SWA_NAME=swa-audit ./tools/create_audit_app.sh
#
# For forks: set AUDIT_HOST to your own host (e.g. audit.example.com) before running.
# For local preview the script also registers http://localhost:4280/ + /index.html.
set -euo pipefail

if [ -n "${SUBSCRIPTION_ID:-}" ]; then
  az account set --subscription "$SUBSCRIPTION_ID" >/dev/null 2>&1 || { echo "ERROR: cannot select subscription $SUBSCRIPTION_ID" >&2; exit 1; }
fi

RG="${RG:-rg-wantnot}"
APP_NAME="${AUDIT_APP_NAME:-WantNot Instant Audit}"
AUDIT_HOST="${AUDIT_HOST:-audit.wantnot.nunan.com}"

# Optional: resolve SWA hostname for wantnot parity check (not required for audit standalone)
SWA_NAME="${SWA_NAME:-}"

TENANT=$(az account show --query tenantId -o tsv)
TENANT_NAME=$(az rest --method get --url 'https://graph.microsoft.com/v1.0/organization?$select=displayName' --query "value[0].displayName" -o tsv 2>/dev/null || echo unknown)
echo "==> Creating audit app in: $TENANT_NAME ($TENANT) for host: $AUDIT_HOST"
if [ -z "${ASSUME_YES:-}" ]; then
  read -r -p "    Correct directory? [y/N] " REPLY
  case "$REPLY" in [yY]*) ;; *) echo "Aborted."; exit 1 ;; esac
fi

REDIRECT="https://${AUDIT_HOST}/"
REDIRECT_HTML="https://${AUDIT_HOST}/index.html"
# Also register without trailing slash canonical form
REDIRECT_NOSLASH="https://${AUDIT_HOST}"

GRAPH_APP_ID="00000003-0000-0000-c000-000000000000"
ORG_READ_ALL_SCOPE="4908d5b9-3fb2-4b1e-9336-1888b7937185"
USER_READ_ALL_SCOPE="a154be20-db9c-4678-8ab7-66f6cc099a59"
AUDITLOG_READ_ALL_SCOPE="e4c9e354-4dc5-45b8-9e7c-e1393b0b1a20"
USER_READ_SCOPE="e1fe6dd8-ba31-4d61-89e7-88639da4683d"

APP_JSON=$(az ad app create \
  --display-name "$APP_NAME" \
  --sign-in-audience AzureADMultipleOrgs \
  --required-resource-accesses "[
    {
      \"resourceAppId\": \"$GRAPH_APP_ID\",
      \"resourceAccess\": [
        {\"id\": \"$USER_READ_SCOPE\",         \"type\": \"Scope\"},
        {\"id\": \"$ORG_READ_ALL_SCOPE\",      \"type\": \"Scope\"},
        {\"id\": \"$USER_READ_ALL_SCOPE\",     \"type\": \"Scope\"},
        {\"id\": \"$AUDITLOG_READ_ALL_SCOPE\", \"type\": \"Scope\"}
      ]
    }
  ]" -o json)

APP_ID=$(echo "$APP_JSON" | jq -r '.appId')
OBJ_ID=$(echo "$APP_JSON" | jq -r '.id')
echo "==> App ID: $APP_ID"

az ad sp create --id "$APP_ID" >/dev/null 2>&1 || true

echo "==> Registering SPA redirect URIs: $REDIRECT, $REDIRECT_HTML, $REDIRECT_NOSLASH + localhost"
az rest --method PATCH \
  --url "https://graph.microsoft.com/v1.0/applications/${OBJ_ID}" \
  --headers 'Content-Type=application/json' \
  --body "{\"spa\":{\"redirectUris\":[\"${REDIRECT}\",\"${REDIRECT_HTML}\",\"${REDIRECT_NOSLASH}\",\"http://localhost:4280/\",\"http://localhost:4280/index.html\"]},\"web\":{\"redirectUris\":[]},\"publicClient\":{\"redirectUris\":[]}}" -o none

echo "    registered:"
az rest --method GET --url "https://graph.microsoft.com/v1.0/applications/${OBJ_ID}?\$select=spa" --query "spa.redirectUris" -o tsv | sed 's/^/      /'

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
echo "==> Writing $ROOT_DIR/config.js"
cat > "$ROOT_DIR/config.js" <<JSCONFIG
/* Generated by tools/create_audit_app.sh — safe to publish.
   A client ID is a public identifier, not a credential. This app is a public
   client with no secret; PKCE is what protects the token exchange. */
window.WANTNOT_AUDIT_CLIENT_ID = '${APP_ID}';
JSCONFIG

cat <<EOF

==========================================================================
  Audit app registered.

  AUDIT_CLIENT_ID = $APP_ID
  Redirects       = $REDIRECT
                  = $REDIRECT_HTML
                  = $REDIRECT_NOSLASH

  No client secret was created. Do not add one — a secret in a browser app
  is a secret you have published.

  Next:
    Store this client ID as GitHub secret AUDIT_CLIENT_ID so deploy.yml can
    inject config.js at build time (forks without the secret still run parity).
    For a one-off local test, config.js was written locally — redeploy is not
    needed locally, but a real custom domain needs:

      AUDIT_HOST=$AUDIT_HOST ./infra/11-custom-domain.sh equivalent (SWA bind + TXT)

  Delegated scopes (all read-only, AuditLog needs a directory role to read sign-ins):
    User.Read, Organization.Read.All, User.Read.All, AuditLog.Read.All
==========================================================================
EOF
