#!/usr/bin/env python3
"""
Parity check: the browser analyzer satisfies the published backend contract.

This repo has no backend — shared/analyzer.py lives in the private
kylernunan/wantnot repo. The contract crosses the repo boundary as two files:

  fixtures/parity_fixtures.json   inputs (mirror of tools/parity_fixtures.json)
  fixtures/parity_expected.json   backend outputs (generated by
                                  tools/parity_snapshot.py in wantnot)

tools/parity_runner.mjs runs the browser analyzer (audit_logic.js) through the
fixtures; this script asserts the output matches the snapshot — finding keys,
seats, money, confidence, waste totals, and warning semantics. A fixture or
analyzer change must regenerate the snapshot in wantnot and sync both files
in the same change (the nightly sync-catalog workflow opens that PR).

    python3 tools/parity_check.py        # verify
"""
from __future__ import annotations

import json
import os
import subprocess
import sys
import tempfile

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
FIXTURES = os.path.join(ROOT, "fixtures", "parity_fixtures.json")
EXPECTED = os.path.join(ROOT, "fixtures", "parity_expected.json")
RUNNER = os.path.join(ROOT, "tools", "parity_runner.mjs")

NODE = os.environ.get("NODE_BIN", "node")
FAIL = 0
results: list[tuple[str, str, str]] = []  # (label, ok, detail)


def check(label: str, ok: bool, detail: str = ""):
    global FAIL
    results.append((label, "ok" if ok else "FAIL", detail))
    if not ok:
        FAIL = 1


def js_side(fixtures_path: str) -> list[dict]:
    """Run the fixtures through the browser analyzer via Node."""
    with tempfile.TemporaryDirectory() as tmp:
        out = os.path.join(tmp, "parity_out.json")
        r = subprocess.run([NODE, RUNNER, fixtures_path, out],
                           capture_output=True, text=True)
        if r.returncode != 0:
            check("node runner exits clean", False, (r.stderr or r.stdout).strip()[:500])
            return []
        return json.load(open(out))


def normalize(findings: list[dict]) -> dict[tuple, dict]:
    """Key findings on kind|sku|upn and keep the money fields, so order and
    record shapes never cause false failures and money-comparison is exact."""
    out = {}
    for f in findings:
        key = (f.get("kind"), f.get("sku_part_number"),
               (f.get("user_principal_name") or "").lower() or None)
        out[key] = {
            "seats": f.get("seats"),
            "annual_cost": round(float(f.get("annual_cost") or 0), 2),
            "confidence": f.get("confidence"),
        }
    return out


def warnings_semantics(warnings: list[str]) -> dict:
    """Reduce warning text to semantic facts, so wording drift between the two
    implementations does not surface as a false divergence — but a real one
    still does."""
    skus = set()
    for w in warnings:
        if w.startswith("No price on file"):
            body = w.split("for:", 1)[1].split(". ", 1)[0]
            skus.update(s.strip() for s in body.split(",") if s.strip())
    return {
        "signin_unavailable": any("sign-in activity" in w.lower() for w in warnings),
        "unknown_price": sorted(skus),
    }


def compare_fixture(fx: dict, exp: dict, js: dict):
    name = fx["name"]
    expn = normalize(exp["findings"])
    jsn = normalize(js["findings"])

    exp_keys = set(expn); js_keys = set(jsn)
    missing = js_keys - exp_keys         # browser finds something backend does not
    extra = exp_keys - js_keys           # backend expects something browser lacks
    if not missing and not extra:
        check(f"{name}: identical finding keys", True)
    else:
        detail = ""
        if missing:
            detail += f"browser-only: {sorted(missing)[:4]} "
        if extra:
            detail += f"backend-only: {sorted(extra)[:4]} "
        check(f"{name}: finding keys match", False, detail)

    diff = []
    for key in sorted(exp_keys & js_keys):
        if expn[key] != jsn[key]:
            diff.append(f"{key}: expected={expn[key]} browser={jsn[key]}")
    check(f"{name}: finding money/seats/confidence match",
          not diff, " ".join(diff)[:200])

    check(f"{name}: annual waste total matches",
          abs(exp["annual_waste_usd"] - js["annual_waste_usd"]) < 0.01,
          f"expected={exp['annual_waste_usd']} browser={js['annual_waste_usd']}")

    exp_sem = exp["warnings_semantics"]
    js_sem = warnings_semantics(js["warnings"])
    for axis in ("signin_unavailable", "unknown_price"):
        a = exp_sem.get(axis)
        b = js_sem.get(axis)
        check(f"{name}: warning[{axis}] agrees", a == b,
              f"expected={a} browser={b}")


def main() -> int:
    fixtures = json.load(open(FIXTURES))["fixtures"]
    expected_all = json.load(open(EXPECTED))["expected"]
    js = js_side(FIXTURES)
    js_by_name = {r["name"]: r for r in js}

    for fx in fixtures:
        name = fx["name"]
        if name not in js_by_name:
            check(f"{name}: browser result present", False, "node produced no result")
            continue
        if name not in expected_all:
            check(f"{name}: snapshot entry present", False,
                  "no backend expectation — regenerate tools/parity_expected.json in wantnot")
            continue
        compare_fixture(fx, expected_all[name], js_by_name[name])

    for name, mark, detail in results:
        flag = "  ok " if mark == "ok" else "FAIL"
        print(f"  [{flag}] {name}" + (f"  — {detail}" if detail and mark == "FAIL" else ""))
    print(f"\n{len(results) - FAIL}/{len(results)} parity assertions")
    print("PASS" if not FAIL else "FAIL")
    return 1 if FAIL else 0


if __name__ == "__main__":
    raise SystemExit(main())
